### ISSUE TITLE
Undefined behavior in Travel_G()

### ISSUE THREAD

**Issue by jinq0123** [asqbtcupid/lua_hotupdate#2]
Assign in the traversal has undefined behavior:

```
for k, v in pairs(t) do
    if k == funcs[1] then t[funcs[2]] = t[k]; t[k] = nil end
```

http://www.lua.org/manual/5.1/manual.html#pdf-next

The behavior of next is undefined if, during the traversal, you assign any value to a non-existent field in the table. You may however modify existing fields. In particular, you may clear existing fields.

**Comment by asqbtcupid** [comment]
Yes,It's a fatal error.
