### ISSUE TITLE
Using a fake ENV, the module's init statements result in noop.

### ISSUE THREAD

**Issue by uvtong** [asqbtcupid/lua_hotupdate#3]
https://github.com/jinq0123/hotfix这个库里面的作者说：

[2] lua_hotupdate 
https://github.com/asqbtcupid/lua_hotupdate 
Lua 5.1.

Using a fake ENV, the module's init statements result in noop.

不能支持5.3么？

**Comment by asqbtcupid** [comment]
是的现在只支持5.1，5.2以后的ENV成了upvalue了，得改一些代码
